### PR TITLE
Add SonarCloud code analysis

### PR DESCRIPTION
**Pull request by oliverhsu77**

### CODE REVIEW

**Comment by Kami** [comment]
I would just recommend disabling the PR comments since it adds a new comment on each push to a PR which can get quite spammy (sadly it doesn't support updating a comment like codecov.io integration does).

**Comment by Kami** [comment]
And you can also add badge to the readme - [Quality Gate Status](https://sonarcloud.io/dashboard?id=scalyr_kafka-connect-scalyr)

```
[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=scalyr_kafka-connect-scalyr&metric=alert_status)](https://sonarcloud.io/dashboard?id=scalyr_kafka-connect-scalyr)
```

It will show correct value once that PR is merged into master and analysis runs on master branch.

**Comment by Kami** [comment]
Since we already run unit tests as part of a maven target and build, it probably also shouldn't be too hard to submit coverage data to sonarcloud (we just need to write coverage data to junit / xunit file and then correctly configure sonar cloud config).

**Comment by oliverhsu77** [comment]
1) Added Jacoco code coverage integrated with Sonar Cloud.
2) Added Sonar Cloud badge to README.

**Pull request merged**
